/** Geofabrik-Importregionen + BBoxes für Routen-Validierung. */

export interface RegionDef {
  code: string
  /** Anzeigename (kurz) */
  label: string
  south: number
  west: number
  north: number
  east: number
  /** Relative Geofabrik-URL unter download.geofabrik.de */
  geofabrikPath: string
  file: string
}

/**
 * Mitteleuropa, Alpen, Benelux, Nord-/Südeuropa, Iberia (inkl. Balearen/Kanaren),
 * GB, IE, NI, IS, GR, CY, MT, AD, Balkan (inkl. XK), Baltikum, FI,
 * FR (Metropole inkl. Korsika). FR-Übersee (DOM/TOM) nicht enthalten.
 * GB = Großbritannien (Geofabrik). NI teilt sich den Ireland-and-Northern-Ireland-Extract mit IE.
 * Plus Hawaii (Geofabrik US-Subextract, außerhalb Europa).
 */
export const IMPORT_REGIONS: RegionDef[] = [
  {
    code: 'AT',
    label: 'Österreich',
    south: 46.4,
    west: 9.5,
    north: 49.1,
    east: 17.2,
    geofabrikPath: 'europe/austria-latest.osm.pbf',
    file: 'austria-latest.osm.pbf',
  },
  {
    code: 'CH',
    label: 'Schweiz',
    south: 45.8,
    west: 5.9,
    north: 47.8,
    east: 10.5,
    geofabrikPath: 'europe/switzerland-latest.osm.pbf',
    file: 'switzerland-latest.osm.pbf',
  },
  {
    code: 'LI',
    label: 'Liechtenstein',
    south: 47.0,
    west: 9.4,
    north: 47.3,
    east: 9.7,
    geofabrikPath: 'europe/liechtenstein-latest.osm.pbf',
    file: 'liechtenstein-latest.osm.pbf',
  },
  {
    code: 'DE',
    label: 'Deutschland',
    south: 47.2,
    west: 5.8,
    north: 55.1,
    east: 15.1,
    geofabrikPath: 'europe/germany-latest.osm.pbf',
    file: 'germany-latest.osm.pbf',
  },
  {
    code: 'IT',
    label: 'Italien',
    south: 36.6,
    west: 6.6,
    north: 47.1,
    east: 18.6,
    geofabrikPath: 'europe/italy-latest.osm.pbf',
    file: 'italy-latest.osm.pbf',
  },
  {
    code: 'SK',
    label: 'Slowakei',
    south: 47.7,
    west: 16.8,
    north: 49.6,
    east: 22.6,
    geofabrikPath: 'europe/slovakia-latest.osm.pbf',
    file: 'slovakia-latest.osm.pbf',
  },
  {
    code: 'SI',
    label: 'Slowenien',
    south: 45.4,
    west: 13.3,
    north: 46.9,
    east: 16.6,
    geofabrikPath: 'europe/slovenia-latest.osm.pbf',
    file: 'slovenia-latest.osm.pbf',
  },
  {
    code: 'CZ',
    label: 'Tschechien',
    south: 48.5,
    west: 12.0,
    north: 51.1,
    east: 18.9,
    geofabrikPath: 'europe/czech-republic-latest.osm.pbf',
    file: 'czech-republic-latest.osm.pbf',
  },
  {
    code: 'HU',
    label: 'Ungarn',
    south: 45.7,
    west: 16.1,
    north: 48.6,
    east: 22.9,
    geofabrikPath: 'europe/hungary-latest.osm.pbf',
    file: 'hungary-latest.osm.pbf',
  },
  {
    code: 'LU',
    label: 'Luxemburg',
    south: 49.44,
    west: 5.73,
    north: 50.19,
    east: 6.53,
    geofabrikPath: 'europe/luxembourg-latest.osm.pbf',
    file: 'luxembourg-latest.osm.pbf',
  },
  {
    code: 'BE',
    label: 'Belgien',
    south: 49.45,
    west: 2.5,
    north: 51.55,
    east: 6.45,
    geofabrikPath: 'europe/belgium-latest.osm.pbf',
    file: 'belgium-latest.osm.pbf',
  },
  {
    code: 'NL',
    label: 'Niederlande',
    south: 50.75,
    west: 3.2,
    north: 53.7,
    east: 7.3,
    geofabrikPath: 'europe/netherlands-latest.osm.pbf',
    file: 'netherlands-latest.osm.pbf',
  },
  {
    code: 'DK',
    label: 'Dänemark',
    south: 54.5,
    west: 8.0,
    north: 57.8,
    east: 15.2,
    geofabrikPath: 'europe/denmark-latest.osm.pbf',
    file: 'denmark-latest.osm.pbf',
  },
  {
    code: 'HR',
    label: 'Kroatien',
    south: 42.35,
    west: 13.4,
    north: 46.55,
    east: 19.45,
    geofabrikPath: 'europe/croatia-latest.osm.pbf',
    file: 'croatia-latest.osm.pbf',
  },
  {
    code: 'ES',
    label: 'Spanien',
    // Festland + Balearen + Kanaren (Geofabrik spain extract)
    south: 27.5,
    west: -18.5,
    north: 43.8,
    east: 4.4,
    geofabrikPath: 'europe/spain-latest.osm.pbf',
    file: 'spain-latest.osm.pbf',
  },
  {
    code: 'PT',
    label: 'Portugal',
    // inkl. Madeira / Azoren (Geofabrik portugal extract)
    south: 32.0,
    west: -31.3,
    north: 42.2,
    east: -6.1,
    geofabrikPath: 'europe/portugal-latest.osm.pbf',
    file: 'portugal-latest.osm.pbf',
  },
  {
    code: 'PL',
    label: 'Polen',
    south: 49.0,
    west: 14.1,
    north: 54.9,
    east: 24.2,
    geofabrikPath: 'europe/poland-latest.osm.pbf',
    file: 'poland-latest.osm.pbf',
  },
  {
    code: 'GB',
    label: 'Großbritannien',
    south: 49.8,
    west: -8.7,
    north: 60.9,
    east: 1.8,
    geofabrikPath: 'europe/great-britain-latest.osm.pbf',
    file: 'great-britain-latest.osm.pbf',
  },
  {
    code: 'NO',
    label: 'Norwegen',
    south: 57.9,
    west: 4.5,
    north: 71.2,
    east: 31.1,
    geofabrikPath: 'europe/norway-latest.osm.pbf',
    file: 'norway-latest.osm.pbf',
  },
  {
    code: 'SE',
    label: 'Schweden',
    south: 55.2,
    west: 10.9,
    north: 69.1,
    east: 24.2,
    geofabrikPath: 'europe/sweden-latest.osm.pbf',
    file: 'sweden-latest.osm.pbf',
  },
  {
    code: 'RO',
    label: 'Rumänien',
    south: 43.5,
    west: 20.2,
    north: 48.3,
    east: 29.8,
    geofabrikPath: 'europe/romania-latest.osm.pbf',
    file: 'romania-latest.osm.pbf',
  },
  {
    code: 'IE',
    label: 'Irland',
    south: 51.4,
    west: -10.5,
    north: 55.5,
    east: -5.9,
    geofabrikPath: 'europe/ireland-and-northern-ireland-latest.osm.pbf',
    file: 'ireland-and-northern-ireland-latest.osm.pbf',
  },
  {
    code: 'NI',
    label: 'Nordirland',
    south: 54.0,
    west: -8.2,
    north: 55.35,
    east: -5.4,
    geofabrikPath: 'europe/ireland-and-northern-ireland-latest.osm.pbf',
    file: 'ireland-and-northern-ireland-latest.osm.pbf',
  },
  {
    code: 'IS',
    label: 'Island',
    south: 63.2,
    west: -24.6,
    north: 66.6,
    east: -13.4,
    geofabrikPath: 'europe/iceland-latest.osm.pbf',
    file: 'iceland-latest.osm.pbf',
  },
  {
    code: 'GR',
    label: 'Griechenland',
    south: 34.5,
    west: 19.2,
    north: 41.8,
    east: 29.8,
    geofabrikPath: 'europe/greece-latest.osm.pbf',
    file: 'greece-latest.osm.pbf',
  },
  {
    code: 'CY',
    label: 'Zypern',
    south: 34.5,
    west: 32.2,
    north: 35.75,
    east: 34.65,
    geofabrikPath: 'europe/cyprus-latest.osm.pbf',
    file: 'cyprus-latest.osm.pbf',
  },
  {
    code: 'MT',
    label: 'Malta',
    south: 35.78,
    west: 14.18,
    north: 36.09,
    east: 14.58,
    geofabrikPath: 'europe/malta-latest.osm.pbf',
    file: 'malta-latest.osm.pbf',
  },
  {
    code: 'AD',
    label: 'Andorra',
    south: 42.42,
    west: 1.38,
    north: 42.66,
    east: 1.79,
    geofabrikPath: 'europe/andorra-latest.osm.pbf',
    file: 'andorra-latest.osm.pbf',
  },
  {
    code: 'BG',
    label: 'Bulgarien',
    south: 41.2,
    west: 22.3,
    north: 44.3,
    east: 28.7,
    geofabrikPath: 'europe/bulgaria-latest.osm.pbf',
    file: 'bulgaria-latest.osm.pbf',
  },
  {
    code: 'RS',
    label: 'Serbien',
    south: 42.2,
    west: 18.8,
    north: 46.2,
    east: 23.1,
    geofabrikPath: 'europe/serbia-latest.osm.pbf',
    file: 'serbia-latest.osm.pbf',
  },
  {
    code: 'BA',
    label: 'Bosnien-Herzegowina',
    south: 42.5,
    west: 15.7,
    north: 45.3,
    east: 19.6,
    geofabrikPath: 'europe/bosnia-herzegovina-latest.osm.pbf',
    file: 'bosnia-herzegovina-latest.osm.pbf',
  },
  {
    code: 'ME',
    label: 'Montenegro',
    south: 41.8,
    west: 18.4,
    north: 43.6,
    east: 20.4,
    geofabrikPath: 'europe/montenegro-latest.osm.pbf',
    file: 'montenegro-latest.osm.pbf',
  },
  {
    code: 'AL',
    label: 'Albanien',
    south: 39.6,
    west: 19.2,
    north: 42.7,
    east: 21.1,
    geofabrikPath: 'europe/albania-latest.osm.pbf',
    file: 'albania-latest.osm.pbf',
  },
  {
    code: 'MK',
    label: 'Nordmazedonien',
    south: 40.8,
    west: 20.4,
    north: 42.4,
    east: 23.0,
    geofabrikPath: 'europe/macedonia-latest.osm.pbf',
    file: 'macedonia-latest.osm.pbf',
  },
  {
    code: 'XK',
    label: 'Kosovo',
    south: 41.85,
    west: 20.0,
    north: 43.3,
    east: 21.8,
    geofabrikPath: 'europe/kosovo-latest.osm.pbf',
    file: 'kosovo-latest.osm.pbf',
  },
  {
    code: 'EE',
    label: 'Estland',
    south: 57.5,
    west: 21.8,
    north: 59.7,
    east: 28.2,
    geofabrikPath: 'europe/estonia-latest.osm.pbf',
    file: 'estonia-latest.osm.pbf',
  },
  {
    code: 'LV',
    label: 'Lettland',
    south: 55.7,
    west: 21.0,
    north: 58.1,
    east: 28.2,
    geofabrikPath: 'europe/latvia-latest.osm.pbf',
    file: 'latvia-latest.osm.pbf',
  },
  {
    code: 'LT',
    label: 'Litauen',
    south: 53.9,
    west: 21.0,
    north: 56.5,
    east: 26.8,
    geofabrikPath: 'europe/lithuania-latest.osm.pbf',
    file: 'lithuania-latest.osm.pbf',
  },
  {
    code: 'FI',
    label: 'Finnland',
    south: 59.8,
    west: 20.0,
    north: 70.1,
    east: 31.6,
    geofabrikPath: 'europe/finland-latest.osm.pbf',
    file: 'finland-latest.osm.pbf',
  },
  // —— Frankreich (Metropole) ——
  {
    code: 'ALS',
    label: 'Elsass',
    south: 47.42,
    west: 6.84,
    north: 49.08,
    east: 8.23,
    geofabrikPath: 'europe/france/alsace-latest.osm.pbf',
    file: 'alsace-latest.osm.pbf',
  },
  {
    code: 'LOR',
    label: 'Lothringen',
    south: 47.77,
    west: 4.88,
    north: 49.62,
    east: 7.64,
    geofabrikPath: 'europe/france/lorraine-latest.osm.pbf',
    file: 'lorraine-latest.osm.pbf',
  },
  {
    code: 'BOU',
    label: 'Bourgogne',
    south: 46.15,
    west: 2.85,
    north: 48.4,
    east: 5.55,
    geofabrikPath: 'europe/france/bourgogne-latest.osm.pbf',
    file: 'bourgogne-latest.osm.pbf',
  },
  {
    code: 'FC',
    label: 'Franche-Comté',
    south: 46.25,
    west: 5.25,
    north: 48.02,
    east: 7.15,
    geofabrikPath: 'europe/france/franche-comte-latest.osm.pbf',
    file: 'franche-comte-latest.osm.pbf',
  },
  {
    code: 'RA',
    label: 'Rhône-Alpes',
    south: 44.05,
    west: 3.85,
    north: 46.52,
    east: 7.25,
    geofabrikPath: 'europe/france/rhone-alpes-latest.osm.pbf',
    file: 'rhone-alpes-latest.osm.pbf',
  },
  {
    code: 'PAC',
    label: "Provence-Alpes-Côte d'Azur",
    south: 42.98,
    west: 4.23,
    north: 45.13,
    east: 7.72,
    geofabrikPath: 'europe/france/provence-alpes-cote-d-azur-latest.osm.pbf',
    file: 'provence-alpes-cote-d-azur-latest.osm.pbf',
  },
  {
    code: 'AQU',
    label: 'Aquitaine',
    south: 42.78,
    west: -1.79,
    north: 45.72,
    east: 1.45,
    geofabrikPath: 'europe/france/aquitaine-latest.osm.pbf',
    file: 'aquitaine-latest.osm.pbf',
  },
  {
    code: 'AUV',
    label: 'Auvergne',
    south: 44.6,
    west: 2.05,
    north: 46.52,
    east: 4.55,
    geofabrikPath: 'europe/france/auvergne-latest.osm.pbf',
    file: 'auvergne-latest.osm.pbf',
  },
  {
    code: 'BNO',
    label: 'Basse-Normandie',
    south: 48.18,
    west: -2.0,
    north: 49.75,
    east: 0.95,
    geofabrikPath: 'europe/france/basse-normandie-latest.osm.pbf',
    file: 'basse-normandie-latest.osm.pbf',
  },
  {
    code: 'BRE',
    label: 'Bretagne',
    south: 47.25,
    west: -5.15,
    north: 48.92,
    east: -1.0,
    geofabrikPath: 'europe/france/bretagne-latest.osm.pbf',
    file: 'bretagne-latest.osm.pbf',
  },
  {
    code: 'CEN',
    label: 'Centre',
    south: 46.35,
    west: 0.05,
    north: 48.95,
    east: 3.15,
    geofabrikPath: 'europe/france/centre-latest.osm.pbf',
    file: 'centre-latest.osm.pbf',
  },
  {
    code: 'CHA',
    label: 'Champagne-Ardenne',
    south: 47.55,
    west: 3.35,
    north: 50.15,
    east: 5.9,
    geofabrikPath: 'europe/france/champagne-ardenne-latest.osm.pbf',
    file: 'champagne-ardenne-latest.osm.pbf',
  },
  {
    code: 'COR',
    label: 'Korsika',
    south: 41.33,
    west: 8.53,
    north: 43.02,
    east: 9.57,
    geofabrikPath: 'europe/france/corse-latest.osm.pbf',
    file: 'corse-latest.osm.pbf',
  },
  {
    code: 'HNO',
    label: 'Haute-Normandie',
    south: 48.7,
    west: 0.05,
    north: 50.08,
    east: 1.8,
    geofabrikPath: 'europe/france/haute-normandie-latest.osm.pbf',
    file: 'haute-normandie-latest.osm.pbf',
  },
  {
    code: 'IDF',
    label: 'Île-de-France',
    south: 48.12,
    west: 1.45,
    north: 49.25,
    east: 3.55,
    geofabrikPath: 'europe/france/ile-de-france-latest.osm.pbf',
    file: 'ile-de-france-latest.osm.pbf',
  },
  {
    code: 'LR',
    label: 'Languedoc-Roussillon',
    south: 42.33,
    west: 1.7,
    north: 44.98,
    east: 4.85,
    geofabrikPath: 'europe/france/languedoc-roussillon-latest.osm.pbf',
    file: 'languedoc-roussillon-latest.osm.pbf',
  },
  {
    code: 'LIM',
    label: 'Limousin',
    south: 44.85,
    west: 0.65,
    north: 46.45,
    east: 2.6,
    geofabrikPath: 'europe/france/limousin-latest.osm.pbf',
    file: 'limousin-latest.osm.pbf',
  },
  {
    code: 'MP',
    label: 'Midi-Pyrénées',
    south: 42.55,
    west: -0.35,
    north: 45.05,
    east: 3.45,
    geofabrikPath: 'europe/france/midi-pyrenees-latest.osm.pbf',
    file: 'midi-pyrenees-latest.osm.pbf',
  },
  {
    code: 'NPC',
    label: 'Nord-Pas-de-Calais',
    south: 50.0,
    west: 1.55,
    north: 51.1,
    east: 4.25,
    geofabrikPath: 'europe/france/nord-pas-de-calais-latest.osm.pbf',
    file: 'nord-pas-de-calais-latest.osm.pbf',
  },
  {
    code: 'PDL',
    label: 'Pays de la Loire',
    south: 46.25,
    west: -2.55,
    north: 48.6,
    east: 0.95,
    geofabrikPath: 'europe/france/pays-de-la-loire-latest.osm.pbf',
    file: 'pays-de-la-loire-latest.osm.pbf',
  },
  {
    code: 'PIC',
    label: 'Picardie',
    south: 48.85,
    west: 1.4,
    north: 50.35,
    east: 4.25,
    geofabrikPath: 'europe/france/picardie-latest.osm.pbf',
    file: 'picardie-latest.osm.pbf',
  },
  {
    code: 'POC',
    label: 'Poitou-Charentes',
    south: 45.05,
    west: -1.6,
    north: 47.15,
    east: 1.2,
    geofabrikPath: 'europe/france/poitou-charentes-latest.osm.pbf',
    file: 'poitou-charentes-latest.osm.pbf',
  },
  // —— Nordamerika ——
  {
    code: 'HI',
    label: 'Hawaii',
    // Hauptinseln (Geofabrik north-america/us/hawaii)
    south: 18.85,
    west: -160.35,
    north: 22.35,
    east: -154.7,
    geofabrikPath: 'north-america/us/hawaii-latest.osm.pbf',
    file: 'hawaii-latest.osm.pbf',
  },
]

export const IMPORT_REGION_CODES = IMPORT_REGIONS.map((r) => r.code)

/** Kurzer Text für UI / Fehlermeldungen. */
export const SUPPORTED_REGIONS_LABEL =
  'AT, CH, LI, DE, DK, IT, SK, SI, CZ, HU, LU, BE, NL, HR, ES (inkl. Balearen/Kanaren), PT, PL, GB, NO, SE, FI, EE, LV, LT, RO, IE, NI, IS, GR, CY, MT, AD, BG, RS, BA, ME, AL, MK, XK, FR (Metropole), HI (Hawaii)'

/**
 * Historisches EU-Fenster — nicht mehr an ORS Geocode gebunden.
 * EU + Hawaii sind disjunkt; Adresssuche läuft weltweit ohne boundary.rect
 * (siehe searchAddresses). Konstante bleibt für Doku/Tooling.
 */
export const GEOCODE_BBOX = {
  minLon: -160.35,
  minLat: 18.85,
  maxLon: 34.7,
  maxLat: 71.2,
} as const
