/** Geofabrik-Importregionen + BBoxes für Routen-Validierung. */

export interface RegionDef {
  code: string
  /** Anzeigename (kurz) */
  label: string
  south: number
  west: number
  north: number
  east: number
  /** Relative Geofabrik-URL unter download.geofabrik.de */
  geofabrikPath: string
  file: string
}

/**
 * Mitteleuropa, Alpen, Benelux, DK, HR, ES, FR (Metropole inkl. Korsika).
 * FR-Übersee (DOM/TOM) nicht enthalten.
 */
export const IMPORT_REGIONS: RegionDef[] = [
  {
    code: 'AT',
    label: 'Österreich',
    south: 46.4,
    west: 9.5,
    north: 49.1,
    east: 17.2,
    geofabrikPath: 'europe/austria-latest.osm.pbf',
    file: 'austria-latest.osm.pbf',
  },
  {
    code: 'CH',
    label: 'Schweiz',
    south: 45.8,
    west: 5.9,
    north: 47.8,
    east: 10.5,
    geofabrikPath: 'europe/switzerland-latest.osm.pbf',
    file: 'switzerland-latest.osm.pbf',
  },
  {
    code: 'LI',
    label: 'Liechtenstein',
    south: 47.0,
    west: 9.4,
    north: 47.3,
    east: 9.7,
    geofabrikPath: 'europe/liechtenstein-latest.osm.pbf',
    file: 'liechtenstein-latest.osm.pbf',
  },
  {
    code: 'DE',
    label: 'Deutschland',
    south: 47.2,
    west: 5.8,
    north: 55.1,
    east: 15.1,
    geofabrikPath: 'europe/germany-latest.osm.pbf',
    file: 'germany-latest.osm.pbf',
  },
  {
    code: 'IT',
    label: 'Italien',
    south: 36.6,
    west: 6.6,
    north: 47.1,
    east: 18.6,
    geofabrikPath: 'europe/italy-latest.osm.pbf',
    file: 'italy-latest.osm.pbf',
  },
  {
    code: 'SK',
    label: 'Slowakei',
    south: 47.7,
    west: 16.8,
    north: 49.6,
    east: 22.6,
    geofabrikPath: 'europe/slovakia-latest.osm.pbf',
    file: 'slovakia-latest.osm.pbf',
  },
  {
    code: 'SI',
    label: 'Slowenien',
    south: 45.4,
    west: 13.3,
    north: 46.9,
    east: 16.6,
    geofabrikPath: 'europe/slovenia-latest.osm.pbf',
    file: 'slovenia-latest.osm.pbf',
  },
  {
    code: 'CZ',
    label: 'Tschechien',
    south: 48.5,
    west: 12.0,
    north: 51.1,
    east: 18.9,
    geofabrikPath: 'europe/czech-republic-latest.osm.pbf',
    file: 'czech-republic-latest.osm.pbf',
  },
  {
    code: 'HU',
    label: 'Ungarn',
    south: 45.7,
    west: 16.1,
    north: 48.6,
    east: 22.9,
    geofabrikPath: 'europe/hungary-latest.osm.pbf',
    file: 'hungary-latest.osm.pbf',
  },
  {
    code: 'LU',
    label: 'Luxemburg',
    south: 49.44,
    west: 5.73,
    north: 50.19,
    east: 6.53,
    geofabrikPath: 'europe/luxembourg-latest.osm.pbf',
    file: 'luxembourg-latest.osm.pbf',
  },
  {
    code: 'BE',
    label: 'Belgien',
    south: 49.45,
    west: 2.5,
    north: 51.55,
    east: 6.45,
    geofabrikPath: 'europe/belgium-latest.osm.pbf',
    file: 'belgium-latest.osm.pbf',
  },
  {
    code: 'NL',
    label: 'Niederlande',
    south: 50.75,
    west: 3.2,
    north: 53.7,
    east: 7.3,
    geofabrikPath: 'europe/netherlands-latest.osm.pbf',
    file: 'netherlands-latest.osm.pbf',
  },
  {
    code: 'DK',
    label: 'Dänemark',
    south: 54.5,
    west: 8.0,
    north: 57.8,
    east: 15.2,
    geofabrikPath: 'europe/denmark-latest.osm.pbf',
    file: 'denmark-latest.osm.pbf',
  },
  {
    code: 'HR',
    label: 'Kroatien',
    south: 42.35,
    west: 13.4,
    north: 46.55,
    east: 19.45,
    geofabrikPath: 'europe/croatia-latest.osm.pbf',
    file: 'croatia-latest.osm.pbf',
  },
  {
    code: 'ES',
    label: 'Spanien',
    south: 35.9,
    west: -9.5,
    north: 43.8,
    east: 4.4,
    geofabrikPath: 'europe/spain-latest.osm.pbf',
    file: 'spain-latest.osm.pbf',
  },
  // —— Frankreich (Metropole) ——
  {
    code: 'ALS',
    label: 'Elsass',
    south: 47.42,
    west: 6.84,
    north: 49.08,
    east: 8.23,
    geofabrikPath: 'europe/france/alsace-latest.osm.pbf',
    file: 'alsace-latest.osm.pbf',
  },
  {
    code: 'LOR',
    label: 'Lothringen',
    south: 47.77,
    west: 4.88,
    north: 49.62,
    east: 7.64,
    geofabrikPath: 'europe/france/lorraine-latest.osm.pbf',
    file: 'lorraine-latest.osm.pbf',
  },
  {
    code: 'BOU',
    label: 'Bourgogne',
    south: 46.15,
    west: 2.85,
    north: 48.4,
    east: 5.55,
    geofabrikPath: 'europe/france/bourgogne-latest.osm.pbf',
    file: 'bourgogne-latest.osm.pbf',
  },
  {
    code: 'FC',
    label: 'Franche-Comté',
    south: 46.25,
    west: 5.25,
    north: 48.02,
    east: 7.15,
    geofabrikPath: 'europe/france/franche-comte-latest.osm.pbf',
    file: 'franche-comte-latest.osm.pbf',
  },
  {
    code: 'RA',
    label: 'Rhône-Alpes',
    south: 44.05,
    west: 3.85,
    north: 46.52,
    east: 7.25,
    geofabrikPath: 'europe/france/rhone-alpes-latest.osm.pbf',
    file: 'rhone-alpes-latest.osm.pbf',
  },
  {
    code: 'PAC',
    label: "Provence-Alpes-Côte d'Azur",
    south: 42.98,
    west: 4.23,
    north: 45.13,
    east: 7.72,
    geofabrikPath: 'europe/france/provence-alpes-cote-d-azur-latest.osm.pbf',
    file: 'provence-alpes-cote-d-azur-latest.osm.pbf',
  },
  {
    code: 'AQU',
    label: 'Aquitaine',
    south: 42.78,
    west: -1.79,
    north: 45.72,
    east: 1.45,
    geofabrikPath: 'europe/france/aquitaine-latest.osm.pbf',
    file: 'aquitaine-latest.osm.pbf',
  },
  {
    code: 'AUV',
    label: 'Auvergne',
    south: 44.6,
    west: 2.05,
    north: 46.52,
    east: 4.55,
    geofabrikPath: 'europe/france/auvergne-latest.osm.pbf',
    file: 'auvergne-latest.osm.pbf',
  },
  {
    code: 'BNO',
    label: 'Basse-Normandie',
    south: 48.18,
    west: -2.0,
    north: 49.75,
    east: 0.95,
    geofabrikPath: 'europe/france/basse-normandie-latest.osm.pbf',
    file: 'basse-normandie-latest.osm.pbf',
  },
  {
    code: 'BRE',
    label: 'Bretagne',
    south: 47.25,
    west: -5.15,
    north: 48.92,
    east: -1.0,
    geofabrikPath: 'europe/france/bretagne-latest.osm.pbf',
    file: 'bretagne-latest.osm.pbf',
  },
  {
    code: 'CEN',
    label: 'Centre',
    south: 46.35,
    west: 0.05,
    north: 48.95,
    east: 3.15,
    geofabrikPath: 'europe/france/centre-latest.osm.pbf',
    file: 'centre-latest.osm.pbf',
  },
  {
    code: 'CHA',
    label: 'Champagne-Ardenne',
    south: 47.55,
    west: 3.35,
    north: 50.15,
    east: 5.9,
    geofabrikPath: 'europe/france/champagne-ardenne-latest.osm.pbf',
    file: 'champagne-ardenne-latest.osm.pbf',
  },
  {
    code: 'COR',
    label: 'Korsika',
    south: 41.33,
    west: 8.53,
    north: 43.02,
    east: 9.57,
    geofabrikPath: 'europe/france/corse-latest.osm.pbf',
    file: 'corse-latest.osm.pbf',
  },
  {
    code: 'HNO',
    label: 'Haute-Normandie',
    south: 48.7,
    west: 0.05,
    north: 50.08,
    east: 1.8,
    geofabrikPath: 'europe/france/haute-normandie-latest.osm.pbf',
    file: 'haute-normandie-latest.osm.pbf',
  },
  {
    code: 'IDF',
    label: 'Île-de-France',
    south: 48.12,
    west: 1.45,
    north: 49.25,
    east: 3.55,
    geofabrikPath: 'europe/france/ile-de-france-latest.osm.pbf',
    file: 'ile-de-france-latest.osm.pbf',
  },
  {
    code: 'LR',
    label: 'Languedoc-Roussillon',
    south: 42.33,
    west: 1.7,
    north: 44.98,
    east: 4.85,
    geofabrikPath: 'europe/france/languedoc-roussillon-latest.osm.pbf',
    file: 'languedoc-roussillon-latest.osm.pbf',
  },
  {
    code: 'LIM',
    label: 'Limousin',
    south: 44.85,
    west: 0.65,
    north: 46.45,
    east: 2.6,
    geofabrikPath: 'europe/france/limousin-latest.osm.pbf',
    file: 'limousin-latest.osm.pbf',
  },
  {
    code: 'MP',
    label: 'Midi-Pyrénées',
    south: 42.55,
    west: -0.35,
    north: 45.05,
    east: 3.45,
    geofabrikPath: 'europe/france/midi-pyrenees-latest.osm.pbf',
    file: 'midi-pyrenees-latest.osm.pbf',
  },
  {
    code: 'NPC',
    label: 'Nord-Pas-de-Calais',
    south: 50.0,
    west: 1.55,
    north: 51.1,
    east: 4.25,
    geofabrikPath: 'europe/france/nord-pas-de-calais-latest.osm.pbf',
    file: 'nord-pas-de-calais-latest.osm.pbf',
  },
  {
    code: 'PDL',
    label: 'Pays de la Loire',
    south: 46.25,
    west: -2.55,
    north: 48.6,
    east: 0.95,
    geofabrikPath: 'europe/france/pays-de-la-loire-latest.osm.pbf',
    file: 'pays-de-la-loire-latest.osm.pbf',
  },
  {
    code: 'PIC',
    label: 'Picardie',
    south: 48.85,
    west: 1.4,
    north: 50.35,
    east: 4.25,
    geofabrikPath: 'europe/france/picardie-latest.osm.pbf',
    file: 'picardie-latest.osm.pbf',
  },
  {
    code: 'POC',
    label: 'Poitou-Charentes',
    south: 45.05,
    west: -1.6,
    north: 47.15,
    east: 1.2,
    geofabrikPath: 'europe/france/poitou-charentes-latest.osm.pbf',
    file: 'poitou-charentes-latest.osm.pbf',
  },
]

export const IMPORT_REGION_CODES = IMPORT_REGIONS.map((r) => r.code)

/** Kurzer Text für UI / Fehlermeldungen. */
export const SUPPORTED_REGIONS_LABEL =
  'AT, CH, LI, DE, DK, IT, SK, SI, CZ, HU, LU, BE, NL, HR, ES, FR (Metropole)'

/** ORS Geocode-Suchfenster (deckt alle Import-BBoxes ab). */
export const GEOCODE_BBOX = {
  minLon: -9.5,
  minLat: 35.9,
  maxLon: 22.9,
  maxLat: 57.8,
} as const
